name: golang-ci

on: [push, pull_request]

jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Linting golang code
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.TOKEN }}
